# -*- coding: utf-8 -*-

"""Generate the Resilient customizations required for rc_servicenow"""

from __future__ import print_function
from resilient_circuits.util import *


def customization_data(client=None):
    """Produce any customization definitions (types, fields, message destinations, etc)
       that should be installed by `resilient-circuits customize`
    """

    # This import data contains:


    yield ImportDefinition(u"""
eyJ0YXNrX29yZGVyIjogW10sICJ3b3JrZmxvd3MiOiBbXSwgImFjdGlvbnMiOiBbXSwgImxheW91
dHMiOiBbXSwgImV4cG9ydF9mb3JtYXRfdmVyc2lvbiI6IDIsICJpZCI6IDksICJpbmR1c3RyaWVz
IjogbnVsbCwgInBoYXNlcyI6IFtdLCAiYWN0aW9uX29yZGVyIjogW10sICJnZW9zIjogbnVsbCwg
InNlcnZlcl92ZXJzaW9uIjogeyJtYWpvciI6IDMwLCAidmVyc2lvbiI6ICIzMC4xLjI1IiwgImJ1
aWxkX251bWJlciI6IDI1LCAibWlub3IiOiAxfSwgInRpbWVmcmFtZXMiOiBudWxsLCAid29ya3Nw
YWNlcyI6IFtdLCAiYXV0b21hdGljX3Rhc2tzIjogW10sICJmdW5jdGlvbnMiOiBbXSwgIm5vdGlm
aWNhdGlvbnMiOiBudWxsLCAicmVndWxhdG9ycyI6IG51bGwsICJpbmNpZGVudF90eXBlcyI6IFt7
ImNyZWF0ZV9kYXRlIjogMTUzNDI1Njg2MDYyMywgImRlc2NyaXB0aW9uIjogIkN1c3RvbWl6YXRp
b24gUGFja2FnZXMgKGludGVybmFsKSIsICJleHBvcnRfa2V5IjogIkN1c3RvbWl6YXRpb24gUGFj
a2FnZXMgKGludGVybmFsKSIsICJpZCI6IDAsICJuYW1lIjogIkN1c3RvbWl6YXRpb24gUGFja2Fn
ZXMgKGludGVybmFsKSIsICJ1cGRhdGVfZGF0ZSI6IDE1MzQyNTY4NjA2MjMsICJ1dWlkIjogImJm
ZWVjMmQ0LTM3NzAtMTFlOC1hZDM5LTRhMDAwNDA0NGFhMCIsICJlbmFibGVkIjogZmFsc2UsICJz
eXN0ZW0iOiBmYWxzZSwgInBhcmVudF9pZCI6IG51bGwsICJoaWRkZW4iOiBmYWxzZX1dLCAic2Ny
aXB0cyI6IFtdLCAidHlwZXMiOiBbXSwgIm1lc3NhZ2VfZGVzdGluYXRpb25zIjogW10sICJpbmNp
ZGVudF9hcnRpZmFjdF90eXBlcyI6IFtdLCAicm9sZXMiOiBbXSwgImZpZWxkcyI6IFt7Im9wZXJh
dGlvbnMiOiBbXSwgInJlYWRfb25seSI6IHRydWUsICJuYW1lIjogImluY190cmFpbmluZyIsICJ0
ZW1wbGF0ZXMiOiBbXSwgInR5cGVfaWQiOiAwLCAiY2hvc2VuIjogZmFsc2UsICJ0ZXh0IjogIlNp
bXVsYXRpb24iLCAiZGVmYXVsdF9jaG9zZW5fYnlfc2VydmVyIjogZmFsc2UsICJleHBvcnRfa2V5
IjogImluY2lkZW50L2luY190cmFpbmluZyIsICJ0b29sdGlwIjogIldoZXRoZXIgdGhlIGluY2lk
ZW50IGlzIGEgc2ltdWxhdGlvbiBvciBhIHJlZ3VsYXIgaW5jaWRlbnQuICBUaGlzIGZpZWxkIGlz
IHJlYWQtb25seS4iLCAicmljaF90ZXh0IjogZmFsc2UsICJvcGVyYXRpb25fcGVybXMiOiB7fSwg
InByZWZpeCI6IG51bGwsICJpbnRlcm5hbCI6IGZhbHNlLCAidmFsdWVzIjogW10sICJibGFua19v
cHRpb24iOiBmYWxzZSwgImlucHV0X3R5cGUiOiAiYm9vbGVhbiIsICJjaGFuZ2VhYmxlIjogdHJ1
ZSwgImhpZGVfbm90aWZpY2F0aW9uIjogZmFsc2UsICJpZCI6IDI2OSwgInV1aWQiOiAiYzNmMGUz
ZWQtMjFlMS00ZDUzLWFmZmItZmU1Y2EzMzA4Y2NhIn1dLCAib3ZlcnJpZGVzIjogW10sICJleHBv
cnRfZGF0ZSI6IDE1MzQyNTQxODkzMjh9
"""
    )
